#QUESTION1
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# Task 1:
empty_array = np.empty((2, 2))
print("Task 1 - Empty Array:\n", empty_array)

# Task 2:
ones_array = np.ones((4, 2))
print("\nTask 2 - All Ones Array:\n", ones_array)

# Task 3:
fill_value_array = np.full((3, 3), 7)  # Example shape and fill value
print("\nTask 3 - Array Filled with 7s:\n", fill_value_array)

# Task 4:
given_array = np.array([[5, 6], [7, 8]])  # Example given array
zeros_like_array = np.zeros_like(given_array)
print("\nTask 4 - Zeros Array with Same Shape as Given Array:\n", zeros_like_array)

# Task 5:
ones_like_array = np.ones_like(given_array)
print("\nTask 5 - Ones Array with Same Shape as Given Array:\n", ones_like_array)

# Task 6:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nTask 6 - Converted Numpy Array:\n", numpy_array)


Task 1 - Empty Array:
 [[4.82158145e-310 0.00000000e+000]
 [2.83895655e+253 6.93861461e-310]]

Task 2 - All Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Task 3 - Array Filled with 7s:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Task 4 - Zeros Array with Same Shape as Given Array:
 [[0 0]
 [0 0]]

Task 5 - Ones Array with Same Shape as Given Array:
 [[1 1]
 [1 1]]

Task 6 - Converted Numpy Array:
 [1 2 3 4]


#QUESTION2
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# Task 1:
array_10_to_49 = np.arange(10, 50)
print("Task 1 - Array from 10 to 49:\n", array_10_to_49)

# Task 2:
matrix_3x3 = np.arange(9).reshape((3, 3))
print("\nTask 2 - 3x3 Matrix with Values 0 to 8:\n", matrix_3x3)

# Task 3:
identity_matrix = np.eye(3)
print("\nTask 3 - 3x3 Identity Matrix:\n", identity_matrix)

# Task 4:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nTask 4 - Mean of Random Array:\n", mean_value)

# Task 5:
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\nTask 5 - Min and Max of 10x10 Random Array:\nMin:", min_value, "Max:", max_value)

# Task 6:
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nTask 6 - Zero Array with 5th Element as 1:\n", zero_array)

# Task 7:
arr = [1, 2, 0, 0, 4, 0]
reversed_array = np.array(arr)[::-1]
print("\nTask 7 - Reversed Array:\n", reversed_array)

# Task 8:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\nTask 8 - 2D Array with Border 1 and Inside 0:\n", border_array)

# Task 9:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nTask 9 - Checkerboard Pattern:\n", checkerboard)


Task 1 - Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Task 2 - 3x3 Matrix with Values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Task 3 - 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Task 4 - Mean of Random Array:
 0.5165125015654222

Task 5 - Min and Max of 10x10 Random Array:
Min: 0.004999273183128206 Max: 0.9810637744977018

Task 6 - Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Task 7 - Reversed Array:
 [0 4 0 0 2 1]

Task 8 - 2D Array with Border 1 and Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Task 9 - Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#QUESTION3
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1:
array_sum = x + y
print("Task 1 - Addition of x and y:\n", array_sum)

# Task 2:
array_diff = x - y
print("\nTask 2 - Subtraction of x and y:\n", array_diff)

# Task 3:
array_multiplied = x * 3
print("\nTask 3 - Multiplication of x by 3:\n", array_multiplied)

# Task 4:
array_squared = np.square(x)
print("\nTask 4 - Square of each element in x:\n", array_squared)

# Task 5:
# v and w
dot_v_w = np.dot(v, w)
print("\nTask 5a - Dot Product of v and w:\n", dot_v_w)

# x and v
dot_x_v = np.dot(x, v)
print("\nTask 5b - Dot Product of x and v:\n", dot_x_v)

# x and y
dot_x_y = np.dot(x, y)
print("\nTask 5c - Dot Product of x and y:\n", dot_x_y)

# Task 6:
concat_x_y_rows = np.concatenate((x, y), axis=0)  # Along rows
print("\nTask 6a - Concatenate x and y along rows:\n", concat_x_y_rows)

concat_v_w_columns = np.vstack((v, w))  # Along columns
print("\nTask 6b - Concatenate v and w along columns:\n", concat_v_w_columns)

# Task 7:
try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("\nTask 7 - Concatenate x and v:\n", concat_x_v)
except ValueError as e:
    print("\nTask 7 - Error encountered when concatenating x and v:")
    print(e)
    print("Explanation: The dimensions of x (2x2) and v (1D array) are incompatible for concatenation along the given axis. To resolve this, v must be reshaped to match the dimensions of x.")


Task 1 - Addition of x and y:
 [[ 6  8]
 [10 13]]

Task 2 - Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Task 3 - Multiplication of x by 3:
 [[ 3  6]
 [ 9 15]]

Task 4 - Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Task 5a - Dot Product of v and w:
 219

Task 5b - Dot Product of x and v:
 [29 77]

Task 5c - Dot Product of x and y:
 [[19 22]
 [50 58]]

Task 6a - Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Task 6b - Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]

Task 7 - Error encountered when concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: The dimensions of x (2x2) and v (1D array) are incompatible for concatenation along the given axis. To resolve this, v must be reshaped to match the dimensions of x.


#QUESTION4
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A⁻¹ = I
A_inv = np.linalg.inv(A)
product_A_A_inv = np.dot(A, A_inv)  # Compute A * A⁻¹

print("1. Prove A.A⁻¹ = I:")
print(product_A_A_inv)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\n2. Prove AB ≠ BA:")
print("AB:\n", AB)
print("BA:\n", BA)
print("Are AB and BA equal? ", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_transpose = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)

print("\n3. Prove (AB)^T = B^T * A^T:")
print("(AB)^T:\n", AB_transpose)
print("B^T * A^T:\n", BT_AT)
print("Are (AB)^T and B^T * A^T equal? ", np.array_equal(AB_transpose, BT_AT))


1. Prove A.A⁻¹ = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. Prove AB ≠ BA:
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Are AB and BA equal?  False

3. Prove (AB)^T = B^T * A^T:
(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Are (AB)^T and B^T * A^T equal?  True
